"""Initial migration

Revision ID: 443c08b3ab80
Revises: 
Create Date: 2026-02-19 23:14:24.868558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443c08b3ab80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('attendance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('study_hours_per_week', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=True),
    sa.Column('placement_status', sa.Enum('PLACED', 'NOT_PLACED', name='placementstatusenum'), nullable=False),
    sa.Column('company_tier', sa.Enum('TIER1', 'TIER2', 'TIER3', name='companytierenum'), nullable=True),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('role_to_major_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_graduation_year'), 'alumni', ['graduation_year'], unique=False)
    op.create_index(op.f('ix_alumni_id'), 'alumni', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_major'), 'alumni', ['major'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('attendance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('study_hours_per_week', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usn', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('college_name', sa.String(), nullable=True),
    sa.Column('is_alumni', sa.Boolean(), nullable=True),
    sa.Column('gpa_trend', sa.String(), nullable=True),
    sa.Column('backlogs', sa.Integer(), nullable=True),
    sa.Column('programming_languages', sa.Text(), nullable=True),
    sa.Column('strongest_skill', sa.String(), nullable=True),
    sa.Column('placement_status', sa.String(), nullable=True),
    sa.Column('biggest_strength', sa.Text(), nullable=True),
    sa.Column('biggest_weakness', sa.Text(), nullable=True),
    sa.Column('habit_to_improve', sa.Text(), nullable=True),
    sa.Column('what_holds_back', sa.Text(), nullable=True),
    sa.Column('career_clarity', sa.Float(), nullable=True),
    sa.Column('chosen_career_path', sa.String(), nullable=True),
    sa.Column('daily_placement_prep', sa.Boolean(), nullable=True),
    sa.Column('interview_fear', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('role_relevance', sa.Float(), nullable=True),
    sa.Column('placement_attempts', sa.Integer(), nullable=True),
    sa.Column('months_to_get_placed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_major'), 'students', ['major'], unique=False)
    op.create_index(op.f('ix_students_usn'), 'students', ['usn'], unique=True)
    op.create_table('behavioral_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('study_hours_per_week', sa.Float(), nullable=True),
    sa.Column('practice_hours_per_day', sa.Float(), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=True),
    sa.Column('project_types', sa.Text(), nullable=True),
    sa.Column('deployed_project', sa.Boolean(), nullable=True),
    sa.Column('internship_exp', sa.Boolean(), nullable=True),
    sa.Column('internship_duration', sa.Integer(), nullable=True),
    sa.Column('problem_solving', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.Column('teamwork', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('attend_lab_regularly', sa.Boolean(), nullable=True),
    sa.Column('submit_assignments_on_time', sa.Boolean(), nullable=True),
    sa.Column('avg_internal_marks', sa.Float(), nullable=True),
    sa.Column('follow_study_schedule', sa.Boolean(), nullable=True),
    sa.Column('concept_revision_frequency', sa.String(), nullable=True),
    sa.Column('online_courses_count', sa.String(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_metrics_id'), 'behavioral_metrics', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('mood_score', sa.Float(), nullable=True),
    sa.Column('focus_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_id'), 'daily_logs', ['id'], unique=False)
    op.create_table('digital_wellbeing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('screen_time_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('educational_app_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('social_media_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('entertainment_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('productivity_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('communication_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('focus_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sleep_duration_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('sleep_bedtime', sa.Time(), nullable=True),
    sa.Column('sleep_wake_time', sa.Time(), nullable=True),
    sa.Column('sleep_quality', sa.Enum('GOOD', 'FAIR', 'POOR', name='sleepqualityenum'), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_date')
    )
    op.create_index(op.f('ix_digital_wellbeing_data_date'), 'digital_wellbeing_data', ['date'], unique=False)
    op.create_index(op.f('ix_digital_wellbeing_data_id'), 'digital_wellbeing_data', ['id'], unique=False)
    op.create_index(op.f('ix_digital_wellbeing_data_student_id'), 'digital_wellbeing_data', ['student_id'], unique=False)
    op.create_table('gap_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('student_value', sa.Float(), nullable=True),
    sa.Column('alumni_average', sa.Float(), nullable=True),
    sa.Column('gap_percentage', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analysis_id'), 'gap_analysis', ['id'], unique=False)
    op.create_table('llm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_logs_id'), 'llm_logs', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='impactenum'), nullable=False),
    sa.Column('estimated_points', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_completed'), 'recommendations', ['completed'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('skill_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('voice_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_assessments_id'), 'skill_assessments', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('proficiency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quiz_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voice_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_weight', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('market_weight_reasoning', sa.Text(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_name', name='uq_student_skill')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skills_student_id'), 'skills', ['student_id'], unique=False)
    op.create_table('student_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_rule', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_activities_date'), 'student_activities', ['date'], unique=False)
    op.create_index(op.f('ix_student_activities_id'), 'student_activities', ['id'], unique=False)
    op.create_index(op.f('ix_student_activities_student_id'), 'student_activities', ['student_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'badge_id')
    )
    op.create_table('student_subject_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_subject_scores_id'), 'student_subject_scores', ['id'], unique=False)
    op.create_table('trajectory_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('margin_of_error', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('trend', sa.Enum('IMPROVING', 'DECLINING', 'STABLE', name='trendenum'), nullable=True),
    sa.Column('velocity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_tier', sa.Enum('TIER1', 'TIER2', 'TIER3', name='companytierenum'), nullable=True),
    sa.Column('num_similar_alumni', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_scores_calculated_at'), 'trajectory_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_trajectory_scores_id'), 'trajectory_scores', ['id'], unique=False)
    op.create_index(op.f('ix_trajectory_scores_student_id'), 'trajectory_scores', ['student_id'], unique=False)
    op.create_table('vector_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('profile_summary', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index(op.f('ix_vector_profiles_id'), 'vector_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_profiles_id'), table_name='vector_profiles')
    op.drop_table('vector_profiles')
    op.drop_index(op.f('ix_trajectory_scores_student_id'), table_name='trajectory_scores')
    op.drop_index(op.f('ix_trajectory_scores_id'), table_name='trajectory_scores')
    op.drop_index(op.f('ix_trajectory_scores_calculated_at'), table_name='trajectory_scores')
    op.drop_table('trajectory_scores')
    op.drop_index(op.f('ix_student_subject_scores_id'), table_name='student_subject_scores')
    op.drop_table('student_subject_scores')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_student_activities_student_id'), table_name='student_activities')
    op.drop_index(op.f('ix_student_activities_id'), table_name='student_activities')
    op.drop_index(op.f('ix_student_activities_date'), table_name='student_activities')
    op.drop_table('student_activities')
    op.drop_index(op.f('ix_skills_student_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_assessments_id'), table_name='skill_assessments')
    op.drop_table('skill_assessments')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_completed'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_llm_logs_id'), table_name='llm_logs')
    op.drop_table('llm_logs')
    op.drop_index(op.f('ix_gap_analysis_id'), table_name='gap_analysis')
    op.drop_table('gap_analysis')
    op.drop_index(op.f('ix_digital_wellbeing_data_student_id'), table_name='digital_wellbeing_data')
    op.drop_index(op.f('ix_digital_wellbeing_data_id'), table_name='digital_wellbeing_data')
    op.drop_index(op.f('ix_digital_wellbeing_data_date'), table_name='digital_wellbeing_data')
    op.drop_table('digital_wellbeing_data')
    op.drop_index(op.f('ix_daily_logs_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_behavioral_metrics_id'), table_name='behavioral_metrics')
    op.drop_table('behavioral_metrics')
    op.drop_index(op.f('ix_students_usn'), table_name='students')
    op.drop_index(op.f('ix_students_major'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_alumni_major'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_id'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_graduation_year'), table_name='alumni')
    op.drop_table('alumni')
    # ### end Alembic commands ###
